name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Question 1
      id: question-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Question 1
        setup-command: ''
        command: What is software engineering?
        input: |-
          A
          B
          C
          D
        expected-output: D
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        QUESTION-1_RESULTS: "${{steps.question-1.outputs.result}}"
      with:
        runners: question-1
